# Generated by Django 3.1.5 on 2021-02-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['price', 'createdAt', '-price', '-createdAt']},
        ),
    ]
