# Generated by Django 3.1.5 on 2021-02-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20210220_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={},
        ),
    ]
